### ISSUE TITLE
Run promote command again on changed service

### ISSUE THREAD

**Issue by schovi** [adidas-group/mashery-toolbelt#10]
Running `promote SERVICE_ID --options` with same options (or almost same) again after changed service like adding, updating or removing endpoints.

**Comment by rathonit1** [comment]
Hi Schovi,
Please correct me whether this change requirement is same as below or not:
Update command for changing values on existing service (and nested resources) & endpoints.
Example: mashery-toolbelt update SERVICE_ID --set="systemDomainAuthentication.password=new_value"
This can be useful for changing value for all endpoints. And it can have similar api as promote command but without creating new one.

**Comment by schovi** [comment]
It is something different. (will make issue).
More for this in post description

**Comment by schovi** [comment]
@rathonit1 Simpliest solution for this seems to "wipe" and fill promoted service again. This would prevent any complicated merging of data. But it relies on fact that you didn't change anything in promoted service or dropping these changes does not matter.
What do you think?

**Comment by schovi** [comment]
@rathonit1 Duplicate of #13 closing this
