### ISSUE TITLE
Add custom error set for a API Service

### ISSUE THREAD

**Issue by rathonit1** [adidas-group/mashery-toolbelt#11]
Add custom error sets when promoting and during creation APIs Service.

**Comment by rathonit1** [comment]
@schovi tested errorset-add command works fine.

As per my knowledge & analysis, we are missing one point over here. 

errorset-add --> this command updates the error set details under mentioned service_id.

but now for each endpoint (under service-id) this new errorset_id has to be updated to actually reflect this updated error set.

for this we need to update endpoint "errors" field with new "errorSet_id".

Please refer (https://api.mashery.com/v3/rest/services/bvvf5yctmy3pzrgjfea2mjwd/endpoints?fields=errors)  GET method for more info.

below is the response for this GET method

{
    "errors": {
        "errorSet": {
            "name": "Problem Detail",
            "id": "6003c09a-9c33-4593-a64c-aa0078ed58f9"
        },
        "userControlledErrorLocation": null,
        "userControlledErrorLocationKey": null
    }
}

let me know if you have any questions.
Thanks,

**Comment by schovi** [comment]
@rathonit1 understand the problem. It is terrible how it is not documented on mashery portal :(

**Comment by rathonit1** [comment]
yes, its missing in documentation. Did hit and trial then got the field name.

**Comment by schovi** [comment]
Added with https://github.com/adidas-group/mashery-toolbelt/commit/46a86de5caf909465abf9fccbf5932f214dbca10 Check it out
