### ISSUE TITLE
(Req) Service endpoint changed & promote

### ISSUE THREAD

**Issue by rathonit1** [adidas-group/mashery-toolbelt#13]
Requirement:
When an existing DEV service Endpoints which has already being cloned and promoted to QA & from QA to PRD for a new service endpoints. 
Now changes are being performed with below two different scenarios in Dev environment that’s needs to get propagate in QA & PRD:

(2b) Dev Service/Endpoints some field value Changes, also need to promote to already promoted QA/PRD service. (Least Priority –can be done after swagger import functionality)

Example: After “performance and integration test or during a new requirement” in DEV environment it is identified to change some methods (GET/OPTIONS/PUT), call transformation or timeout values for different endpoint 
Now to sync these changes from DEV to QA or from QA to PRD we need to have a command to sync these values.

**Comment by schovi** [comment]
@rathonit1 Simpliest solution for this seems to "wipe" and fill promoted service again. This would prevent any complicated merging of data. But it relies on fact that you didn't change anything in promoted service or dropping these changes does not matter.
What do you think?

**Comment by rathonit1** [comment]
@schovi For #12 and #13 we can not simply "wipe" them out.

Reason: Since there is a dependency of endpoints IDs with Package & Plan. If we wipe (i.e. delete endpoints ids), than there will be an impact on Package and Plan designer.
Here again we need to add these endpoints. that is not simple as we need to know in which package & plan these endpoint ids are added & it will become more complex. 
Also it will create downtime for existing endpoints during this activity and no one will accept it (in PRD env).
We can have a conversation over call on this.

**Comment by schovi** [comment]
@rathonit1 I understand. Will think about better effective solution

**Comment by rathonit1** [comment]
@schovi we can ignore this enhancement.
