### ISSUE TITLE
Backup/Restore Package Plan

### ISSUE THREAD

**Issue by rathonit1** [adidas-group/mashery-toolbelt#15]
Need to have functionality for Package & Plan to be able to backup & restore similar to service backup and restore command (least priority).

**Comment by rathonit1** [comment]
@schovi 
our plan is to restore content if required to earlier stage (restore data that we backup-ed up with help of "backup-package <packageId> [backupName]" command). 

So need to address 'restore-package' command.

FYI 
--backup (working)
$mashery-toolbelt backup-package 7c5e6f95-***525f DemoTest5Play
--restore (not working)
$ mashery-toolbelt package DemoTest5Play.json
Creating package from blueprint file 'DemoTest5Play.json'
â£¾  (node:5140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Blueprint contains errors:
The prop `organization` is marked as required in `blueprint`, but its value is `undefined`.
(node:5140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
â£

**Comment by schovi** [comment]
@rathonit1 Somehow mistakenly I did not implement restoring of package backups. Implemented with `mashery-toolbelt@2.0.40` Same logic as for services now:

```
    backup <serviceId> [backupName]           Backup all data for given service
    restore <serviceId> <backupName>          Restore given service from existing backup
    backup-package <packageId> [backupName]   Backup all data for given service
    restore-package <packageId> <backupName>  Restore given service from existing backup
```

**Comment by schovi** [comment]
If working feel free to close

**Comment by rathonit1** [comment]
Testing passed.
