### ISSUE TITLE
swagge-import --name='*:DEV (Play) *'

### ISSUE THREAD

**Issue by rathonit1** [adidas-group/mashery-toolbelt#20]
As we know when we do swagger-import, swagger file generally contains sample name/title as '[Demo] Approval API'

now in command when we use --name='*:DEV (Play) *'  this introduces name as follows: 
"DEV (Play) (Demo) Approval API" in Mashery.
this does not look good. so as per my thinking we should ignore [Demo], so that name will look like "DEV (Play) Approval API" in Mashery. once you get spare time, please have a look into this. let me know if more details are required.

**Comment by rathonit1** [comment]
@schovi can you please help on this. now people started using this functionality

**Comment by schovi** [comment]
@rathonit1 You can always do `[DEMO] *:DEV (Play) *` 
Only exception is I internaly replace `[]` with `()` when parsing swagger import. So it should be in replacer too to prevent confusion.

**Comment by schovi** [comment]
@rathonit1 good catch. Once it is `outboundTransportProtocol` which I set. And other is `inboundSslRequired` which I ignored skipped.

**Comment by rathonit1** [comment]
@schovi this topic is already addressed, can be closed.
