### ISSUE TITLE
Include rate limit information in response headers property is not propagated during promotion

### ISSUE THREAD

**Issue by oonovak** [adidas-group/mashery-toolbelt#21]
Include rate limit information in response headers property is not propagated during promotion.
<img width="341" alt="screen shot 2018-03-08 at 13 41 29" src="https://user-images.githubusercontent.com/25197625/37151621-828be628-22d6-11e8-8274-3b823287982b.png">

**Comment by schovi** [comment]
@oonovak Fixed with `mashery-toolbelt@2.0.18`
Field `rateLimitHeadersEnabled` was not in list of fields in documentation.
