### ISSUE TITLE
Concern over update "mashery-toolbelt package <Name>"

### ISSUE THREAD

**Issue by rathonit1** [adidas-group/mashery-toolbelt#33]
About update of service (swagger-import) and package, I am having one concern.
If we use simple `mashery-toolbelt package DEV-package-bluprint.yml` command to create or update with some automation tool, and user by mistake or unknowingly uses existing package name which was used by some other project, then how we can warn user or stop such process. As we are going to follow similar steps for service creation/update with single command. So we need some suggestions on  this topic, as at present we don’t have control on selection of package name.

**Comment by rathonit1** [comment]
@schovi if really require we can "Warn !!!" user (in a nice way). like his operation will update/change/impact existing 'Package/Plan' or 'Service'... 
So that if user performs update by mistake or unknowingly, can cancel the operations that he is performing.

**Comment by schovi** [comment]
Good catch. This is simple.

**Comment by schovi** [comment]
@rathonit1 Can be like this? I have feeling like I am stuck in this "diff" concept and there can be a better solution :)

![f98a3494-5593-47dc-9a00-7b319cb16077](https://user-images.githubusercontent.com/11453/42779322-62ea80ec-8940-11e8-914f-b7cad9115c7f.jpg)

**Comment by rathonit1** [comment]
@schovi  Yh this should be fine. please release this version I will test and provide you feedback if any changes requires.
one question: does this will show what are the changes going to get implemented right?

Thanks,

**Comment by schovi** [comment]
@rathonit1 `mashery-toolbelt@2.0.41`

**Comment by rathonit1** [comment]
working
